version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
      - bookstore-network  
    environment:
      MONGO_URI: xyzValue
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - bookstore-network  
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bookstore-network   
    volumes:
      - mongo-data:/data/db

networks:
  bookstore-network:  
    driver: bridge

volumes:
  mongo-data:
    driver: local
