version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
      - bookstore-network
    environment:
      MONGO_URI: xyzValue
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - bookstore-network
    environment:
      REACT_APP_API_URL: http://backend:5050

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bookstore-network
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker
    environment:
      DOCKER_HOST: "tcp://docker:2375"  # Specify Docker host (optional)
    privileged: true  # Enable privileged mode for Docker access inside Jenkins container
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  jenkins_home:
    driver: local
